version: "3"
services: 
    node-app:
        build: 
            context: . 
            args:
                NODE_ENV: production
        ports: 
            - "5000:5000"
        environment: 
            - NODE_ENV=production
        command:    node server.js