const mongoose=require('mongoose')
const EventSchema=new mongoose.Schema({
Eventname:{
    type:String,
    required:true
},
starttime:{
    type:Date,
    required:true
},
endtime:{
    type:Date,
    required:true
},
Eventduration:{
type:String,
required:true
},
prize:{
    type:String,
    required:true
},
registeredusers:[
    {
        type:mongoose.Types.ObjectId,
        ref:"FestEventRegisteredUser"
    }
],
Eventdetail:{
    type:String,
    required:true
},
rules:{
    type:String,
    required:true
},
contestType:{
    type:String,
    enum:['ongoing','upcoming','previous'],
    required:true
}
})
module.exports=mongoose.model('FestEvent',EventSchema)