const mongoose=require('mongoose')
const FestEventRegisterSchema=new mongoose.Schema({
            Name:{
                type:String,
            },
            email:{
                type:String,  
            },
            PhoneNo:{
                type:Number,
            },
            branch:{
                type:String
            },
            college:{
                type:String
            },
            year:{
                type:String
            },
            YmcaCurrency:{
                type:Number,
                default:0
            },
            Eventname:{
                type:String,
                default:null
            },
            EventId:{
                type:String,
                default:null
            },
})
module.exports=mongoose.model("FestEventRegisteredUser",FestEventRegisterSchema);